services:
  db:
    image: postgres:16
    container_name: library_db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: library_system
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: library_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: library_redis
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: library_api_app
    restart: always
    ports:
      - "8081:8081"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: library_system

      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: ""
      REDIS_DB: "0"

      JWT_SECRET: "ini_adalah_kunci_rahasia_yang_sangat_panjang"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  pgadmin_data:
